title: 九州地方の自然と産業
style: https://optgeo.github.io/b3p/style.json
chapters:
  -
    title: 大村湾
    description: >-
      真珠とナマコが名産品です。大村湾の天然真珠は古来より有名ですが、
      現在は真珠の養殖が盛んです。大村湾のナマコは身が柔らかいです。
    hash: 11.2/32.9982/129.8242/138.3/64
  -
    title: 筑紫平野
    description: >-
      海抜約5m以下の低地では、クリークと呼ばれる水路が発達し、
      独特の水郷景観を形成しています。米作が盛んです。
    hash: 10.89/33.2094/130.4286/14.9/62
  -
    title: 阿蘇山
    description: >-
      阿蘇山は世界最大級のカルデラです。
    hash: 10.82/32.9178/131.0562/109.3/63
  -
    title: 大分
    description: >-
      石油化学や鉄鋼の生産が盛んです。
    hash: 14.68/33.27065/131.67556/-116.9/80
footer: >-
  <p>YAML と GitHub Actions と
  <a href='https://optgeo.github.io/b3p/#15.7/35.680899/139.766841/0/49'>b3p</a>で
  <a href='https://github.com/mapbox/storytelling'>storytelling</a>しています。</p>
  <p>このプロジェクトは、
  <a href='https://github.com/optgeo'>Adopt Geodata プロジェクト</a>の一環です。</p>
  <p>地理空間情報は人間の安全保障に貢献するデータですが、
  人々のプライバシーや社会の安全に関わる悪用も可能な情報です。</p>
  <p>適切な<a href='https://ggim.un.org/'>情報管理</a>を行い、
  <a href='https://www.mofa.go.jp/mofaj/files/100167362.pdf'>信頼を大切に</a>しながら
  <a href='https://www.cas.go.jp/jp/seisaku/sokuitiri/index.html'>地理空間情報の活用を推進</a>
  しましょう。</p>
