name: render config.js
on:
  push:
    branches: [ main ]
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: render config.js
      run: |
        rake config
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add docs/config.js
        git commit -m 'update'
        git push origin main
